### ISSUE TITLE
Consider using autograd for all gradient calculations

### ISSUE THREAD

**Issue by shoyer** [fancompute/angler#31]
Hi there -- Angler looks like an interesting project!

You probably know this already, but Autograd supports defining custom "primitive" operations: https://github.com/HIPS/autograd/blob/master/docs/tutorial.md#extend-autograd-by-defining-your-own-primitives

If you used primitive operations to define gradients for a forward simulation (from the adjoint rule), you could let Autograd handle end-to-end gradient calculations for you. This would be very elegant, and probably much easier to maintain and extend. You could get rid of most of your `gradients.py` module, for example.

Autograd doesn't support sparse matrices, so unfortunately you can't get this entirely automatically. But it *would* work to define a primitive function `simulate_electric_field()` that maps from relative permittivity to resulting electric fields. The "vjp" function Autograd needs to define derivatives is basically exactly the adjoint rule.

**Comment by twhughes** [comment]
Hi Stephan, thanks!

This is definitely something that has been on my mind for a while now and an excellent suggestion.

A few months ago, I tried out some simple tests of this idea using a fork of Autograd that supports sparse matrices, you can see them [here](https://github.com/twhughes/autograd/blob/scipy-sparse/spsolve_test.py) (kind of messy code at the moment).  

For whatever reason, these seem much slower than hard coding the adjoint gradients directly.  I'm not sure if this has to do with some of the internals of autograd, the fork I am using, or whether I am just not doing it correctly.  I've also thought about writing this in pytorch, however I'm not sure if I'll run into the same issue.  In your mind, would defining the gradients using autogad primitives, as you've desrcibed, come with a performance cost?

Also, is this a basic sketch of your idea?

One could define a primitive function for solving the electric fields, say
```
@primitive
def simulate_electic_field(eps_r, *args):
     # construct the system matrix from eps_r and other args.
     # solve AE = b
     # return E
```
The jvp (where `v` is the vector) would look something like this
```
def vjp(E, eps_r, v, *args):
     # construct A (or use saved, and/or factorized A)
     # construct dE/deps
     # vjp = spsolve(A.T, v.T) @ dA/deps @ E
```

Then the idea is to use this vjp, along with the partial of the objective function with respect to E, to compute the full gradients?

This would certainly make things more elegant.  I wonder how it would work with the nonlinear field solutions where one must solve `A(E) E = b`.  Perhaps each nonlinearity will need to define its own jvp.

Thanks for the comment and interest in angler!

**Comment by shoyer** [comment]
> In your mind, would defining the gradients using autogad primitives, as you've desrcibed, come with a performance cost?

No, it should be basically free. Autograd won't be doing anything with sparse matrices, it will be doing almost exactly the same calculation you are currently doing by hand.

I think you have this formulated correctly. There are some complex conjugates, too (though I'm not entirely sure they're necessary): 
```python
def vjp_maker(E, eps_r):
    def vjp(v):
        # Takes v = d(objective)/dE; returns d(objective)/d(eps_r)
        # Construct A (or use saved, and/or factorized A)
        adjoint = spsolve(A.T.conj(), v.conj())
        return adjoint.conj() @ dA/d(eps) @ E
    return vjp

defvjp(simulate_electic_field, vjp_maker)
```

I like Dolphin-Adjoint's notes on the adjoint rule if you're looking for a simpler reference: http://www.dolfin-adjoint.org/en/latest/documentation/maths/

The beauty of autograd is that once you set this up, you don't need to use the JVP function explicitly. You just define a function of `simulate_electic_field()` and call `autograd.grad()` on it. 

For non-linear fields, you have a different matrix A to invert. Also, instead of dA/d(eps) being the identity matrix you would add another contribution from the non-linearity. But you still only solve a single adjoint equation -- a wonderful fact of the adjoint rule is that it is always linear, even if the equation you are solving is non-linear. You don't need a separate JVP for each nonlinearity -- only a separate term in dA/deps.

**Comment by twhughes** [comment]
@shoyer I just implemented this idea and it seems to work!  At least for linear, Ez polarization right now.

[Code is here](https://github.com/fancompute/angler/blob/autograd_tests/autograd_tests/adjoint_autograd.py) on the `autograd_tests` branch I created.

**Comment by twhughes** [comment]
@shoyer Just want to mention that we released a new project, [ceviche](https://github.com/twhughes/ceviche), which basically uses HIPS autograd to compute gradients for both FDTD and FDFD.  We'll be working on integrating these into angler in the near future.  Thanks again for your suggestion earlier!

**Comment by shoyer** [comment]
@twhughes awesome to see that!

One other primitive we came up with might be useful is for solving a generic sparse matrix given in COO format:
```python
# Copyright 2019 Google LLC.
# SPDX-License-Identifier: Apache-2.0

@autograd.primitive
def solve_coo(a_entries, a_indices, b):
  """Solve a sparse system of linear equations.

  Args:
    a_entries: numpy array with shape (num_zeros,) giving values for non-zero
      matrix entries.
    a_indices: numpy array with shape (2, num_zeros) giving x and y indices for
      non-zero matrix entries.
    b: 1d numpy array specifying the right hand side of the equation.

  Returns:
    1d numpy array corresponding to the solution of a*x=b.
  """
  a = scipy.sparse.coo_matrix((a_entries, a_indices), shape=(b.size,)*2).tocsc()
  return scipy.sparse.linalg.spsolve(a, b)

# see autograd's np.linalg.solve:
# https://github.com/HIPS/autograd/blob/96a03f44da43cd7044c61ac945c483955deba957/autograd/numpy/linalg.py#L40

def solve_coo_adjoint(a_entries, a_indices, b):
  return solve_coo(anp.conj(a_entries), a_indices[::-1], anp.conj(b))

def grad_solve_coo_entries(ans, a_entries, a_indices, b):
  def jvp(grad_ans):
    lambda_ = solve_coo_adjoint(a_entries, a_indices, grad_ans)
    i, j = a_indices
    return -lambda_[i] * ans[j]
  return jvp

def _grad_undefined(_, *args):
  raise TypeError('gradient undefined for this input argument')

def grad_solve_coo_b(ans, a_entries, a_indices, b):
  def jvp(grad_ans):
    return solve_coo_adjoint(a_entries, a_indices, grad_ans)
  return jvp

autograd.extend.defvjp(
    solve_coo, grad_solve_coo_entries, _grad_undefined, grad_solve_coo_b)
```

**Comment by twhughes** [comment]
This looks super useful!  Thanks for sending!  Does it pass tests against numerical derivatives?  I'm wondering if there should be a `np.conj` in the line containing `return -lambda_[i] * ans[j]`.

**Comment by shoyer** [comment]
You should double check the complex conjugates. I only wrote tests for real
valued input.

**Comment by twhughes** [comment]
Hey @shoyer, do you mind if we integrate this code ^^^ (or something similar) in `angler` or `ceviche`?  Just want to make sure this is ok with Google, for example.

Planning to do a merge of the two packages (`angler` as a higher order wrapper for `ceviche`) and replace the ugly primitives of ceviche with something more low level, like what you sent.

Thanks, Tyler

**Comment by shoyer** [comment]
The code is owned by Google but you can use it under an Apache 2.0 license,
that's why I put that in the header. Or if you prefer another license, I'd
be happy to toss it into a pull request, just let me know.

**Comment by twhughes** [comment]
Hey @shoyer, I got around to writing these sparse matrix primitives with the intention of porting them into the FDFD solvers soon.  The code is based on what you pasted here but I modified it a bit and added forward-mode gradients and made sparse_matrix-vector products a primitive.

[Here's the code if you're curious.](https://github.com/fancompute/ceviche/blob/sp_primitive/ceviche/primitives.py)

```python primtiives.py``` runs some gradient checking.

[And here's a little demo for an FDFD-like problem](https://github.com/fancompute/ceviche/blob/sp_primitive/test_demos/simple_test.py). 

I am still stuck on implementing sparse-matrix by sparse-matrix multiplication.  I was wondering if you have any insight on how to define the vjp for this.  [The function in question is here.](https://github.com/fancompute/ceviche/blob/sp_primitive/ceviche/primitives.py#L200)

Do you have any ideas on how to implement this vjp?  This one runs without errors but the gradients it returns are incorrect.  I've been a bit confused at how to do this and since you wrote some similar vjps I was hoping you might have some insight. 

This would be the final piece of the puzzle before I can port this into the main fdfd solver of ceviche.

Thanks for your help and discussions!

**Comment by twhughes** [comment]
Update: I just used the formalism where you solve for E, rather than H.  This makes the system matrix twice as big in Hz polarization, but it lets you use autograd to define the primitives, so I'll take that tradeoff.. The current master branch of ceviche (and the PyPI version) both support this now.

**Comment by twhughes** [comment]
another update, I finally got the sparse-sparse multiplication up and running.  https://github.com/fancompute/ceviche/blob/master/ceviche/primitives.py#L273

**Comment by shoyer** [comment]
Nice!

**Comment by BhattacharyaSumit** [comment]
@twhughes Hi.
I have a problem regarding defining the autograd.extend.defvjp function. 
```
def compute_je(U, edof, xs , penalS, phi, j0, jl, beta):
  je = xs**penalS + j0 * (1/4) * anp.sum(anp.exp(beta * anp.matmul(U[edof],phi)-1),1)
  je_check  = je < -jl
  #je = je._value
  je_check = list(compress(range(len(je_check)), je_check))
  if len(je_check)>0:
    je[je_check]=0 
  je = anp.array(je)
  return je , je_check

```
This is my function. How can I use autograd.extend.defvjp it. 
Here U is a 1D array, edof is a 2d array of indices, phi is a 2d array, xs is 1d.  I need to calculate the gradient of je with respect to U[edof]. 
I am wondering , how to stitch it together with the defvjp function.

**Comment by twhughes** [comment]
hi @BhattacharyaSumit i'm afraid this probably isn't the right place for getting help on this problem.

Perhaps you could post it to the main [autograd](https://github.com/HIPS/autograd) repository.

You can also take some inspiration from [this file](https://github.com/fancompute/ceviche/blob/master/ceviche/primitives.py#L16) and the documentation and examples in it.  I defined some primitives for sparse linear algebra.

One thing i noticed of the top of my head is that if you want to differentiate with respect to `U[edof]`, you're probably better off making a separate function with the value of `U[edof]` as an argument, instead of `U` and `edof` separately.  Also, see if autograd can differentiate your function automatically without needing to define your own vjp.  And if not, it could be worth writing it in a different form that might be compatible with autograd.

Hope this helps.  Unfortunately for more guidance you'll have to read through the autograd repository and associated examples.
